resources:
    - ./resources/deployment.yml
    - ./resources/ingress-route.yml
    
      
configMapGenerator:
- name: configuration-ui
  env: ./resources/.env
  options:
    disableNameSuffixHash: true