resources:
    - ./resources/deployment.yml
    - ./resources/ingress-route.yml
    
      
#configMapGenerator:
#- name: configuration-sso
#  literals:
#  - JAVA_HOME=/opt/java/jdk
#  - JAVA_TOOL_OPTIONS=-agentlib:hprof  
#  options:
#    disableNameSuffixHash: true
#    annotations:
#      dashboard: "1"
#    labels:
#        test: plop
##transformers: