apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-cert
  namespace: default
spec:
  commonName: api-preprod.azko.app
  secretName: api-cert-preprod
  dnsNames:
    - api-preprod.azko.app
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer