apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: api
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`api-preprod.azko.app`)
      kind: Rule
      services:
        - name: upsell-crm-api-preprod
          port: 80
  tls:
    secretName: api-cert-preprod