resources:
    - ./resources/deployment.yml
    - ./resources/ingress-route.yml
    
      
configMapGenerator:
- name: api-configuration
  env: ./resources/.env
  options:
    disableNameSuffixHash: true
    
#transformers: