resources:
#    - ./resources/configmap.yml
    - ./resources/deployment.yml
    
      
configMapGenerator:
- name: api-configuration
  literals:
  - APP_VERSION=$BUILD_SOURCEBRANCH
  options:
    disableNameSuffixHash: true
    
    
#transformers: