resources:
    - ./resources/deployment.yml
    
configMapGenerator:
- name: api-configuration
  env: ./resources/.env
  options:
    disableNameSuffixHash: true
    
secretGenerator:
- name: api-secret
  envs:
  - ./resources/.env.secret
  type: Opaque
  options:
    disableNameSuffixHash: true    
#transformers: