resources:
    - ./resources/deployment.yml
    - ./resources/ingress-route.yml
    
      
configMapGenerator:
- name: api-configuration
  literals:
  - APP_VERSION=$BUILD_SOURCEBRANCH
  options:
    disableNameSuffixHash: true
    
    
#transformers: