apiVersion: kustomize.config.k8s.io/v1alpha1  # <-- Component notation
kind: Component

resources:
    - ./resources/deployment.yml
    
configMapGenerator:
- name: database-configuration
  env: ./resources/.env
  options:
    disableNameSuffixHash: true

secretGenerator:
- name: database-secret
  envs:
  - ./resources/.env.secret
  type: Opaque
  options:
    disableNameSuffixHash: true