apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ui-cert
spec:
  commonName: upsell.azko.app
  secretName: ui-cert-prod
  dnsNames:
    - upsell.azko.app
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer