apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sso-cert
spec:
  commonName: sso.azko.app
  secretName: sso-cert-prod
  dnsNames:
    - sso.azko.app
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer