apiVersion: batch/v1
kind: Job
metadata:
  name: api-update
spec:
  template:
    spec:
      containers:
      - name: api-update-job
        image: api
        command: ["php",  "bin/console", "-wle", "upsell:organisations:update-all"]
        envFrom:
        - configMapRef:
            name: api-configuration
        - secretRef:
            name: api-secret
      restartPolicy: Never
  backoffLimit: 4