namePrefix: upsell-crm-
nameSuffix:  -preprod
namespace: upsell-crm-preprod

components:
  - ../../../components/database/
  
resources:
  - ./resources/volume-claim.yml
  - ./resources/volume.yml
  
replacements:
- source:
    kind: Deployment
    fieldPath: metadata.name
  targets:
  - select: 
      name: my-resource

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/volumes/0
      value:
        name: mysql-storage
        persistentVolumeClaim:
        claimName: database-pvc  
  target:
    kind: Deployment
      


  