apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 2
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: mysql
          ports:
          - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: tcp-mysql
  selector:
    app: database