apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: database-pv
  
  
apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
spec:
  storageClassName: ""
  claimRef:
    name: database-pvc