resources:
    - ./resources/deployment.yml
    - ./resources/job.yml
 
configMapGenerator:
- name: sso-configuration
  env: ./resources/.env
  options:
    disableNameSuffixHash: true

secretGenerator:
- name: sso-secret
  envs:
  - ./resources/.env.secret
  type: Opaque
  options:
    disableNameSuffixHash: true
