resources:
    - ./resources/configmap.yml
    - ./resources/deployment.yml
 
configMapGenerator:
- name: sso-configuration
  literals:
  - APP_VERSION=$BUILD_SOURCEBRANCH
  options:
    disableNameSuffixHash: true
      
#configMapGenerator:
#- name: configuration-sso
#  literals:
#  - JAVA_HOME=/opt/java/jdk
#  - JAVA_TOOL_OPTIONS=-agentlib:hprof  
#  options:
#    disableNameSuffixHash: true
#    annotations:
#      dashboard: "1"
#    labels:
#        test: plop
#transformers: