apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ui-cert
spec:
  commonName: upsell-preprod.azko.app
  secretName: ui-cert-preprod
  dnsNames:
    - upsell-preprod.azko.app
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer