namePrefix: upsell-crm-
nameSuffix:  -prod
namespace: upsell-crm-prod

resources:
  - ../../../base/sso/
  - ./resources/cert.yml
  - ./resources/ingress-route.yml
  
  
images:
    - name: sso
      newName: rg.fr-par.scw.cloud/azko-upsell/$SSO_IMAGE
      newTag: $SSO_IMAGE_TAG
      
      
configMapGenerator:
- name: sso-configuration
  behavior: merge
  env: ./resources/.env
  options:
    disableNameSuffixHash: true
    