resources:
    - ./resources/namespace.yml
    - ./resources/configmap.yml
    - ./resources/sso.yml
    - ./resources/api.yml
    - ./resources/ui.yml
    
      
configMapGenerator:
- name: configuration-sso
  literals:
  - JAVA_HOME=/opt/java/jdk
  - JAVA_TOOL_OPTIONS=-agentlib:hprof  
  options:
    disableNameSuffixHash: true
    annotations:
      dashboard: "1"
    labels:
        test: plop
#transformers: