apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: sso
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`$DOMAIN`)
      kind: Rule
      services:
        - name: sso
          port: 80
  tls:
    resolver: myresolver
#    secretName: sso-cert