apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: api-update-job
        image: api
        command: ["php",  "bin/console", "-wle", "upsell:organisations:update-all"]
      restartPolicy: Never
  backoffLimit: 4