apiVersion: batch/v1
kind: Job
metadata:
  name: sso-update
spec:
  template:
    spec:
      containers:
      - name: sso-update-job
        image: sso
        command: ["php",  "bin/console", "-wle", "upsell:organisations:update-all"]
        envFrom:
        - configMapRef:
            name: sso-configuration
        - secretRef:
            name: sso-secret
      restartPolicy: Never
  backoffLimit: 4