apiVersion: batch/v1
kind: Job
metadata:
  name: sso-update
spec:
  template:
    spec:
      containers:
      - name: sso-update-job
        image: sso
        command: ["php",  "bin/console", "upsell:organisations:update-all"]
        envFrom:
        - configMapRef:
            name: sso-configuration
        - secretRef:
            name: sso-secret
        volumeMounts:
            - name: database-credentials-storage
              mountPath: $DB_CREDENTIALS_PATH
      volumes:
        - name: database-credentials-storage
          emptyDir: {}
      restartPolicy: Never
  backoffLimit: 4