appnameVersion: apps/v1
kind: Deployment
metadata:
  name: appname
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appname
  template:
    metadata:
      labels:
        app: appname
    spec:
      containers:
        - name: appname
          image: appname
          ports:
          - containerPort: 80
      imagePullSecrets:
        - name: registry-secret
---
appnameVersion: v1
kind: Service
metadata:
  name: appname
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: appname