apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sso-cert
spec:
  commonName: sso-preprod.azko.app
  secretName: sso-cert-preprod
  dnsNames:
    - sso-preprod.azko.app
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer