apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-cert
  namespace: default
spec:
  commonName: api.azko.app
  secretName: api-cert-prod
  dnsNames:
    - api.azko.app
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer